
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVISIONEQ = 25;
  public static final int POW = 38;
  public static final int FUNCTION = 54;
  public static final int BOOLEANLIT = 10;
  public static final int RANDOM = 48;
  public static final int STRINGLIT = 11;
  public static final int UMINUS = 47;
  public static final int TIMESEQ = 24;
  public static final int CASE = 42;
  public static final int LPAREN = 26;
  public static final int CONTINUE = 6;
  public static final int MINUS = 19;
  public static final int RPAREN = 27;
  public static final int AND = 37;
  public static final int NOT = 34;
  public static final int IDENTIFER = 12;
  public static final int OR = 36;
  public static final int IN = 8;
  public static final int COMMA = 50;
  public static final int PLUSEQ = 22;
  public static final int GEQ = 17;
  public static final int MINUSEQ = 23;
  public static final int NUMBERLIT = 9;
  public static final int PLUS = 18;
  public static final int IF = 44;
  public static final int DOT = 51;
  public static final int BOOLEAN = 58;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int error = 1;
  public static final int INCLUDE = 2;
  public static final int LCURLY = 28;
  public static final int NEWLINE = 52;
  public static final int EQEQ = 14;
  public static final int NUMBER = 56;
  public static final int MOD = 35;
  public static final int CONSTANT = 53;
  public static final int BREAK = 5;
  public static final int VOID = 55;
  public static final int EQ = 13;
  public static final int SWITCH = 41;
  public static final int FILENAME = 3;
  public static final int RCURLY = 29;
  public static final int TIMES = 20;
  public static final int COLON = 49;
  public static final int FOREACH = 40;
  public static final int ELSE = 45;
  public static final int LANGLE = 33;
  public static final int LSQUARE = 30;
  public static final int ENUM = 60;
  public static final int WHILE = 39;
  public static final int RSQUARE = 31;
  public static final int LIST = 59;
  public static final int DEFAULT = 43;
  public static final int RANGLE = 32;
  public static final int LEQ = 16;
  public static final int STRING = 57;
  public static final int STRUCT = 61;
  public static final int DIVISION = 21;
  public static final int NAN = 4;
  public static final int NOTEQ = 15;
  public static final int IDENTIFIER = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INCLUDE",
  "FILENAME",
  "NAN",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "IN",
  "NUMBERLIT",
  "BOOLEANLIT",
  "STRINGLIT",
  "IDENTIFER",
  "EQ",
  "EQEQ",
  "NOTEQ",
  "LEQ",
  "GEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVISION",
  "PLUSEQ",
  "MINUSEQ",
  "TIMESEQ",
  "DIVISIONEQ",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "LSQUARE",
  "RSQUARE",
  "RANGLE",
  "LANGLE",
  "NOT",
  "MOD",
  "OR",
  "AND",
  "POW",
  "WHILE",
  "FOREACH",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "IF",
  "ELSE",
  "IDENTIFIER",
  "UMINUS",
  "RANDOM",
  "COLON",
  "COMMA",
  "DOT",
  "NEWLINE",
  "CONSTANT",
  "FUNCTION",
  "VOID",
  "NUMBER",
  "STRING",
  "BOOLEAN",
  "LIST",
  "ENUM",
  "STRUCT"
  };
}

