ANTLR = java -jar antlr-4.9.3-complete.jar

# --------------------------------------------------

Simpleton:
	ANTLR Simpleton.g4 -Dlanguage=CSharp -visitor


clean:
	rm -f *.cs
	rm -f *.interp
	rm -f *.tokens
	