//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Simpleton.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SimpletonParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface ISimpletonVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SimpletonParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] SimpletonParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.primitiv_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiv_type([NotNull] SimpletonParser.Primitiv_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SimpletonParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCall</c>
	/// labeled alternative in <see cref="SimpletonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] SimpletonParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="SimpletonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] SimpletonParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConstantLiteral</c>
	/// labeled alternative in <see cref="SimpletonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantLiteral([NotNull] SimpletonParser.ConstantLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NaNExpr</c>
	/// labeled alternative in <see cref="SimpletonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNaNExpr([NotNull] SimpletonParser.NaNExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParensExpr</c>
	/// labeled alternative in <see cref="SimpletonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParensExpr([NotNull] SimpletonParser.ParensExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InfixExpr</c>
	/// labeled alternative in <see cref="SimpletonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInfixExpr([NotNull] SimpletonParser.InfixExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="SimpletonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] SimpletonParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember([NotNull] SimpletonParser.MemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] SimpletonParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_decl([NotNull] SimpletonParser.Variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.const_variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConst_variable_decl([NotNull] SimpletonParser.Const_variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.list_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_decl([NotNull] SimpletonParser.List_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.list_initialize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_initialize([NotNull] SimpletonParser.List_initializeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.struct_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_decl([NotNull] SimpletonParser.Struct_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.struct_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_member([NotNull] SimpletonParser.Struct_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.enum_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_decl([NotNull] SimpletonParser.Enum_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.enum_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_member([NotNull] SimpletonParser.Enum_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.function_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_decl([NotNull] SimpletonParser.Function_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_type([NotNull] SimpletonParser.Return_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.formal_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_parameter([NotNull] SimpletonParser.Formal_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] SimpletonParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.jump_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJump_stmt([NotNull] SimpletonParser.Jump_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_stmt([NotNull] SimpletonParser.Return_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.switch_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_stmt([NotNull] SimpletonParser.Switch_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.switch_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_case([NotNull] SimpletonParser.Switch_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.switch_case_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_case_default([NotNull] SimpletonParser.Switch_case_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.if_else_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_else_stmt([NotNull] SimpletonParser.If_else_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.else_if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_if_stmt([NotNull] SimpletonParser.Else_if_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.else_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_stmt([NotNull] SimpletonParser.Else_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_stmt([NotNull] SimpletonParser.While_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.foreach_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeach_stmt([NotNull] SimpletonParser.Foreach_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] SimpletonParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign_stmt([NotNull] SimpletonParser.Assign_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.ternary_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTernary_stmt([NotNull] SimpletonParser.Ternary_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.compound_assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_assign_stmt([NotNull] SimpletonParser.Compound_assign_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_call([NotNull] SimpletonParser.Func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpletonParser.actual_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_parameter_list([NotNull] SimpletonParser.Actual_parameter_listContext context);
}
