
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVISIONEQ = 27;
  public static final int DIVIDE = 52;
  public static final int POW = 44;
  public static final int FUNCTION = 58;
  public static final int SQRT = 42;
  public static final int BOOLEANLIT = 15;
  public static final int INTEGERLIT = 13;
  public static final int STRINGLIT = 16;
  public static final int UMINUS = 53;
  public static final int TIMESEQ = 26;
  public static final int CASE = 48;
  public static final int INTEGER = 6;
  public static final int LPAREN = 28;
  public static final int CONTINUE = 3;
  public static final int CBRT = 43;
  public static final int MINUS = 21;
  public static final int RPAREN = 29;
  public static final int AND = 41;
  public static final int NOT = 38;
  public static final int OR = 40;
  public static final int IN = 5;
  public static final int COMMA = 56;
  public static final int GEQ = 37;
  public static final int PLUSEQ = 24;
  public static final int MINUSEQ = 25;
  public static final int PLUS = 20;
  public static final int MAIN = 54;
  public static final int IF = 49;
  public static final int LSQURE = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int DECIMAL = 7;
  public static final int RETURN = 4;
  public static final int error = 1;
  public static final int RSQURE = 33;
  public static final int LCURLY = 30;
  public static final int NEWLINE = 55;
  public static final int EQEQ = 18;
  public static final int MOD = 39;
  public static final int DECIMALLIT = 14;
  public static final int CONSTANT = 57;
  public static final int BREAK = 2;
  public static final int VOID = 59;
  public static final int EQ = 17;
  public static final int SWITCH = 47;
  public static final int RCURLY = 31;
  public static final int TIMES = 22;
  public static final int FOREACH = 46;
  public static final int ELSE = 50;
  public static final int LANGLE = 35;
  public static final int ENUM = 11;
  public static final int WHILE = 45;
  public static final int LIST = 10;
  public static final int RANGLE = 34;
  public static final int LEQ = 36;
  public static final int STRING = 8;
  public static final int DIVISION = 23;
  public static final int STRUCT = 12;
  public static final int NOTEQ = 19;
  public static final int IDENTIFIER = 51;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "IN",
  "INTEGER",
  "DECIMAL",
  "STRING",
  "BOOLEAN",
  "LIST",
  "ENUM",
  "STRUCT",
  "INTEGERLIT",
  "DECIMALLIT",
  "BOOLEANLIT",
  "STRINGLIT",
  "EQ",
  "EQEQ",
  "NOTEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVISION",
  "PLUSEQ",
  "MINUSEQ",
  "TIMESEQ",
  "DIVISIONEQ",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "LSQURE",
  "RSQURE",
  "RANGLE",
  "LANGLE",
  "LEQ",
  "GEQ",
  "NOT",
  "MOD",
  "OR",
  "AND",
  "SQRT",
  "CBRT",
  "POW",
  "WHILE",
  "FOREACH",
  "SWITCH",
  "CASE",
  "IF",
  "ELSE",
  "IDENTIFIER",
  "DIVIDE",
  "UMINUS",
  "MAIN",
  "NEWLINE",
  "COMMA",
  "CONSTANT",
  "FUNCTION",
  "VOID"
  };
}

